apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zoneminder-server-ingress
  namespace: zoneminder
  annotations:
    nginx.ingress.kubernetes.io/server-alias: "192.168.1.19"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    external-dns.alpha.kubernetes.io/hostname: zm.rent-ix.app
    external-dns.alpha.kubernetes.io/target: b20f8ff6-7a49-4f53-a138-9aad8dea8cbf.cfargotunnel.com

spec:
  ingressClassName: nginx
  rules:
    - host: zm.rent-ix.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zoneminder-svc
                port:
                  number: 80
